# Generated by Django 4.1 on 2022-08-25 07:33

import django.core.validators
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='changeme')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField(default=1900, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1900)])),
                ('desc', models.TextField(default='Not provided')),
                ('poster', models.ImageField(default='movie.jpg', upload_to='posters')),
                ('screens', models.ImageField(blank=True, upload_to='')),
                ('taggs_plus', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
