# Generated by Django 4.1 on 2022-08-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='screens',
            new_name='screenshots',
        ),
    ]
