# Generated by Django 4.1 on 2022-08-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_rename_desc_movie_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='taggs_plus',
            new_name='tags',
        ),
    ]
