# Generated by Django 4.1 on 2022-09-10 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_rename_taggs_plus_movie_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(default='USA', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=6, default='0.01', max_digits=9, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
