# Generated by Django 4.1 on 2022-10-23 13:31

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='changeme', max_length=500)),
                ('title', models.TextField(max_length=300)),
                ('year', models.PositiveSmallIntegerField(default=1900, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1900)])),
                ('rating', models.DecimalField(decimal_places=6, default='0.01', max_digits=9, validators=[django.core.validators.MaxValueValidator(10)])),
                ('poster', models.ImageField(default='movie.jpg', max_length=500, upload_to='posters')),
                ('screenshots', models.ImageField(blank=True, upload_to='')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=500), blank=True, size=None)),
                ('cast', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=1000), blank=True, size=None)),
                ('plot', models.TextField(default='spoilers coming..', max_length=5000)),
                ('countries', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=300), blank=True, default=movies.models.clear_list, size=None)),
            ],
        ),
    ]
