# Generated by Django 4.1 on 2022-11-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieworld',
            name='voters_number',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
