# Generated by Django 4.1 on 2022-11-06 09:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movieworld_voters_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieworld',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=500), blank=True, default=[], size=None),
        ),
    ]
