# Generated by Django 4.1 on 2022-11-06 11:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieworld_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieworld',
            name='genre',
        ),
        migrations.AddField(
            model_name='movieworld',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=500), blank=True, default=[], size=None),
        ),
    ]
