# Generated by Django 4.1 on 2022-11-06 11:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movieworld_genre_movieworld_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieworld',
            name='countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=300), blank=True, default=[], size=None),
        ),
    ]
