# Generated by Django 4.1 on 2022-11-06 11:26

import django.contrib.postgres.fields
from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movieworld_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieworld',
            name='countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=300), blank=True, default=movies.models.clear_list, size=None),
        ),
        migrations.AlterField(
            model_name='movieworld',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=500), blank=True, default=movies.models.clear_list, size=None),
        ),
    ]
