# Generated by Django 4.1 on 2022-11-16 22:09

import django.contrib.postgres.fields
from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movieworld_countries_alter_movieworld_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieworld',
            name='director',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=1000), blank=True, default=movies.models.clear_list, size=None),
        ),
    ]
